export const anonArray = [
  "Santa",
  "Elf",
  "Christmas Tree",
  "Turkey",
  "Holiday Spirit",
  "KEVINNN",
  "KEERTHIII",
  "Nutcracker",
  "Snowman",
  "Jingle Bell",
  "Dasher",
  "Dancer",
  "Prancer",
  "Vixen",
  "Comet",
  "Cupid",
  "Donner",
  "Blitzen",
  "Rudolph",
  "Chestnuts Roasting on an Open Fire",
  "Snowball",
  "Evergreen",
  "Ice Skate",
  "Cranberry",
  "Buddy the Elf",
  "Candle",
  "Giftbox",
  "Mitten",
  "Eggnog",
  "Gingerbread",
  "All I Want for Christmas is You",
  "Wreath",
  "Candy Cane",
  "Hot Cocoa",
  "Chocolate Cake",
  "Icicle",
  "Cider",
  "39-and-a-half-foot Pole",
  "Scarf",
  "Sled",
  "Mariah Carey",
  "Reindeer",
  "Sweater",
  "Cornucopia",
  "Bademjoon",
  "Menorah",
  "Pilgrim",
  "Plymouth Rock",
  "Fireplace",
  "Bauble",
  "Pumpkin",
  "Pecan Pie",
  "Carols",
  "Stocking",
  "Coal",
  "Sugarplum",
  "Grandma got run over by a reindeer",
  "Scrooge",
  "Grinch",
  "Ornament",
];
