export const anonArray = [
    'Crimson',
    'Bear',
    'Wildcat',
    'Tiger',
    'Razorback',
    'Golden Eagle',
    'Raider',
    'Bluejay',
    'Knight',
    'Owl',
    'Paladin',
    'Bronco',
    'Antelope',
    'Bison',
    'Hawkeye',
    'Cyclone',
    'Jayhawk',
    'Golden Flash',
    'Cajun',
    'Hurricane',
    'Spartan',
    'Bobcat',
    'Wolfpack',
    'Norse',
    'Lion',
    'Panther',
    'Horned Frog',
    'Musketeer',
    'Boilermaker',
    'Redhawk',
    'Longhorn',
    'Aggie',
    'Mountaineer',
    'Husky',
    'Trojan',
    'Ram',
    'Cavalier',
];
