export const anonArray = [
    'Skittles',
    'Snickers',
    'Ghost',
    'Milky Way',
    'Starburst',
    "Reese's Cup",
    'Candy Corn',
    'Pumpkin',
    'Tootsie Roll',
    'Jolly Rancher',
    'Spooky Skeleton',
    'Sour Patch Kid',
    'Lifesaver',
    "Hershey's Bar",
    'Werewolf',
    'Kitkat',
    'Almond Joy',
    'Vampire',
    'Smarties',
    'M&M',
    'Bat',
    'Twix',
    'Crunch Bar',
    'Gobstopper',
    'Junior Mint',
    'Black Cat',
    'Jelly Bean',
    'Swedish Fish',
    'Rolo',
    'Mike',
    'Ike',
    'Gummy Bear',
    'Zombie',
    'Twizzler',
    'Haunted 2-4 Tree',
    'Taffy',
    'Multivitamin',
    'Ring Pop',
    'Spooky Peep',
    'Gumball',
    'Pixistick',
    'Wizard',
    'Halloween',
];
