export const anonArray = [
    'Bunny',
    'Jester',
    'Sunflower',
    'Blanket',
    'Teddy Bear',
    'Kitty',
    'Pumpkin',
    'Scheme',
    'Fate',
    'Jamba Juice',
    'Truck',
    'Trinket',
    'Essence',
    'Perfume',
    'Breeze',
    'Light',
    'Vacation',
    'Heart',
    'Cupid',
    'Flower',
    'Rose',
    'Valentine',
    'Poem',
    'Diamond',
    'Chocolate',
    'Candy',
    'Arrow',
    'Destiny',
    'Moon',
    'Star',
    'Kirby'
];